language: node_js
before_script:
- ./prebuild.sh
- gem install sass -v 3.4.25
env:
  global:
  - GH_REPO="laraconfbrasil/website"
script: docpad generate
deploy:
  skip_cleanup: true
  provider: script
  script: docpad deploy-ghpages --env static
  on:
    all_branches: true
