language: node_js
before_script:
- ./prebuild.sh
- gem install sass -v 3.4.25
env:
  global:
  - GH_REPO="laraconfbrasil/website"

stages:
  - name: build
    script: docpad generate
  - name: deploy
    script: docpad deploy-ghpages --env static
#    if: branch = master
