language: node_js
before_script:
- ./prebuild.sh
- gem install sass -v 3.4.25
env:
  global:
  - GH_REPO="laraconfbrasil/website"
script: docpad generate
after_success:
 # - test $TRAVIS_BRANCH = "master" &&
   - docpad deploy-ghpages --env static
