language: node_js
before_script:
- chmod +x ./prebuild.sh
- ./prebuild.sh
- gem install sass -v 3.4.25
env:
  global:
  - GH_REPO="laraconfbrasil/website"
script: docpad generate
deploy:
  provider: script
  script: docpad deploy-ghpages --env static
  on:
    branch: master
