language: node_js
before_script:
- chmod +x ./prebuild.sh
- ./prebuild.sh
- gem install sass -v 3.4.25
script:
- docpad deploy-ghpages --env static
env:
  global:
  - GH_REPO="laraconfbrasil/website"
branches:
  only:
  - master
